<div align="center">
  <h1> 30 Days Of Python: Day 20 - PIP </h1>
  <a class="header-badge" target="_blank" href="https://www.linkedin.com/in/asabeneh/">
  <img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social">
  </a>
  <a class="header-badge" target="_blank" href="https://twitter.com/Asabeneh">
  <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/asabeneh?style=social">
  </a>

<sub>Author:
<a href="https://www.linkedin.com/in/asabeneh/" target="_blank">Asabeneh Yetayeh</a><br>
<small>Second Edition: July, 2021</small>
</sub>
</div>

[<< Day 19](../19_Day_File_handling/19_file_handling.md) | [Day 21 >>](../21_Day_Classes_and_objects/21_classes_and_objects.md)


- [📘 Day 20](#-day-20)
  - [Python PIP - Python 패키지 관리자](#python-pip---python-패키지-관리자)
    - [PIP란?](#pip란)
    - [PIP 설치하기](#pip-설치하기)
    - [pip를 사용하여 패키지 설치하기](#pip를-사용하여-패키지-설치하기)
    - [패키지 제거하기](#패키지-제거하기)
    - [패키지 목록](#패키지-목록)
    - [패키지 정보 보기](#패키지-정보-보기)
    - [PIP Freeze](#pip-freeze)
    - [URL에서 읽기](#url에서-읽기)
    - [패키지 만들기](#패키지-만들기)
    - [패키지에 대한 추가 정보](#패키지에-대한-추가-정보)
  - [연습문제: Day 20](#연습문제-day-20)

# 📘 Day 20

## Python PIP - Python 패키지 관리자

### PIP란?

PIP는 Preferred installer program의 약자입니다. _pip_를 사용하여 다양한 Python 패키지를 설치합니다.
패키지는 하나 이상의 모듈이나 다른 패키지를 포함할 수 있는 Python 모듈입니다. 애플리케이션에 설치할 수 있는 모듈 또는 모듈들이 패키지입니다.
프로그래밍에서 모든 유틸리티 프로그램을 직접 작성할 필요 없이 패키지를 설치하고 애플리케이션에 임포트합니다.

### PIP 설치하기

pip를 설치하지 않았다면 지금 설치해 봅시다. 터미널 또는 명령 프롬프트로 이동하여 다음을 복사하여 붙여넣으세요:

```sh
asabeneh@Asabeneh:~$ pip install pip
```


다음을 입력하여 pip가 설치되었는지 확인하세요

```sh
pip --version
```

In [ ]:
asabeneh@Asabeneh:~$ pip --version
pip 21.1.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.9.6)


보시다시피 pip 버전 21.1.3을 사용하고 있습니다. 이보다 약간 낮거나 높은 숫자가 보이면 pip가 설치된 것입니다.

다양한 목적으로 Python 커뮤니티에서 사용되는 패키지들을 확인해 봅시다. 다양한 애플리케이션에 사용할 수 있는 많은 패키지가 있다는 것을 알아두세요.

### pip를 사용하여 패키지 설치하기

numeric python이라고 불리는 _numpy_를 설치해 봅시다. 머신 러닝과 데이터 과학 커뮤니티에서 가장 인기 있는 패키지 중 하나입니다.

- NumPy는 Python을 이용한 과학 컴퓨팅을 위한 기본 패키지입니다. 다음과 같은 것들을 포함하고 있습니다:
  - 강력한 N차원 배열 객체
  - 정교한 (브로드캐스팅) 함수
  - C/C++ 및 Fortran 코드를 통합하기 위한 도구
  - 유용한 선형 대수, 푸리에 변환 및 난수 기능

```sh
asabeneh@Asabeneh:~$ pip install numpy
```


numpy를 사용해 봅시다. Python 대화형 셸을 열고 python을 입력한 다음 다음과 같이 numpy를 임포트하세요:

In [ ]:
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version.version
'1.20.1'
>>> lst = [1, 2, 3,4, 5]
>>> np_arr = numpy.array(lst)
>>> np_arr
array([1, 2, 3, 4, 5])
>>> len(np_arr)
5
>>> np_arr * 2
array([ 2,  4,  6,  8, 10])
>>> np_arr  + 2
array([3, 4, 5, 6, 7])
>>>


Pandas는 Python 프로그래밍 언어를 위한 고성능, 사용하기 쉬운 데이터 구조 및 데이터 분석 도구를 제공하는 오픈 소스, BSD 라이선스 라이브러리입니다. numpy의 큰형인 _pandas_를 설치해 봅시다:

```sh
asabeneh@Asabeneh:~$ pip install pandas
```

In [ ]:
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas


이 섹션은 numpy나 pandas에 대한 것이 아니라 패키지를 설치하고 임포트하는 방법을 배우는 것입니다. 필요하다면 다른 섹션에서 다양한 패키지에 대해 이야기할 것입니다.

웹 브라우저 모듈을 임포트해 봅시다. 이 모듈은 어떤 웹사이트든 열 수 있도록 도와줍니다. 이 모듈은 설치할 필요가 없으며 Python 3에 기본적으로 이미 설치되어 있습니다. 예를 들어 언제든지 여러 웹사이트를 열거나 일정을 예약하고 싶다면 이 _webbrowser_ 모듈을 사용할 수 있습니다.

In [ ]:
import webbrowser # 웹사이트를 열기 위한 웹 브라우저 모듈

# URL 목록: python
url_lists = [
    'http://www.python.org',
    'https://www.linkedin.com/in/asabeneh/',
    'https://github.com/Asabeneh',
    'https://twitter.com/Asabeneh',
]

# 위의 웹사이트 목록을 다른 탭에서 엽니다
for url in url_lists:
    webbrowser.open_new_tab(url)


### 패키지 제거하기

설치된 패키지를 유지하고 싶지 않다면 다음 명령을 사용하여 제거할 수 있습니다.

```sh
pip uninstall packagename
```


### 패키지 목록

컴퓨터에 설치된 패키지를 보려면 pip 뒤에 list를 사용할 수 있습니다.

```sh
pip list
```


### 패키지 정보 보기

패키지에 대한 정보를 보려면

```sh
pip show packagename
```

```sh
asabeneh@Asabeneh:~$ pip show pandas
Name: pandas
Version: 1.2.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires: python-dateutil, pytz, numpy
Required-by:
```


더 자세한 정보를 원하면 --verbose를 추가하면 됩니다

```sh
asabeneh@Asabeneh:~$ pip show --verbose pandas
Name: pandas
Version: 1.2.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires: numpy, pytz, python-dateutil
Required-by:
Metadata-Version: 2.1
Installer: pip
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Operating System :: OS Independent
  Intended Audience :: Science/Research
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Programming Language :: Python :: 3.7
  Programming Language :: Python :: 3.8
  Programming Language :: Cython
  Topic :: Scientific/Engineering
Entry-points:
  [pandas_plotting_backends]
  matplotlib = pandas:plotting._matplotlib
```


### PIP Freeze

설치된 Python 패키지와 해당 버전을 생성하며 출력은 requirements 파일에 사용하기에 적합합니다. requirements.txt 파일은 Python 프로젝트에 설치된 모든 Python 패키지를 포함해야 하는 파일입니다.

```sh
asabeneh@Asabeneh:~$ pip freeze
docutils==0.11
Jinja2==2.7.2
MarkupSafe==0.19
Pygments==1.6
Sphinx==1.2.2
```


pip freeze는 사용되고 설치된 패키지와 해당 버전을 제공합니다. 배포를 위해 requirements.txt 파일과 함께 사용합니다.

### URL에서 읽기

이제 로컬 머신에 있는 파일을 읽거나 쓰는 방법에 익숙해졌습니다. 때때로 url을 사용하여 웹사이트에서 읽거나 API에서 읽고 싶을 수 있습니다.
API는 Application Program Interface의 약자입니다. 서버 간에 구조화된 데이터, 주로 json 데이터를 교환하는 수단입니다. 네트워크 연결을 열려면 _requests_라는 패키지가 필요합니다. 이 패키지는 네트워크 연결을 열고 CRUD(생성, 읽기, 업데이트, 삭제) 작업을 구현할 수 있게 해줍니다. 이 섹션에서는 CRUD의 읽기 또는 가져오기 부분만 다룰 것입니다.

_requests_를 설치해 봅시다:

In [ ]:
asabeneh@Asabeneh:~$ pip install requests


_requests_ 모듈에서 _get_, _status_code_, _headers_, _text_ 및 _json_ 메서드를 살펴보겠습니다:
  - _get()_: 네트워크를 열고 url에서 데이터를 가져옵니다 - response 객체를 반환합니다
  - _status_code_: 데이터를 가져온 후 작업 상태를 확인할 수 있습니다 (성공, 오류 등)
  - _headers_: 헤더 타입을 확인합니다
  - _text_: 가져온 response 객체에서 텍스트를 추출합니다
  - _json_: json 데이터를 추출합니다
이 웹사이트에서 txt 파일을 읽어 봅시다, https://www.w3.org/TR/PNG/iso_8859-1.txt.

In [ ]:
import requests # request 모듈을 임포트합니다

url = 'https://www.w3.org/TR/PNG/iso_8859-1.txt' # 웹사이트의 텍스트

response = requests.get(url) # 네트워크를 열고 데이터를 가져옵니다
print(response)
print(response.status_code) # 상태 코드, 성공:200
print(response.headers)     # 헤더 정보
print(response.text) # 페이지의 모든 텍스트를 제공합니다

```sh
<Response [200]>
200
{'date': 'Sun, 08 Dec 2019 18:00:31 GMT', 'last-modified': 'Fri, 07 Nov 2003 05:51:11 GMT', 'etag': '"17e9-3cb82080711c0;50c0b26855880-gzip"', 'accept-ranges': 'bytes', 'cache-control': 'max-age=31536000', 'expires': 'Mon, 07 Dec 2020 18:00:31 GMT', 'vary': 'Accept-Encoding', 'content-encoding': 'gzip', 'access-control-allow-origin': '*', 'content-length': '1616', 'content-type': 'text/plain', 'strict-transport-security': 'max-age=15552000; includeSubdomains; preload', 'content-security-policy': 'upgrade-insecure-requests'}
```


- API에서 읽어 봅시다. API는 Application Program Interface의 약자입니다. 서버 간에 구조화된 데이터, 주로 json 데이터를 교환하는 수단입니다. API의 예시: https://restcountries.eu/rest/v2/all. _requests_ 모듈을 사용하여 이 API를 읽어 봅시다.

In [ ]:
import requests
url = 'https://restcountries.eu/rest/v2/all'  # 국가 API
response = requests.get(url)  # 네트워크를 열고 데이터를 가져옵니다
print(response) # response 객체
print(response.status_code)  # 상태 코드, 성공:200
countries = response.json()
print(countries[:1])  # 첫 번째 국가만 슬라이스했습니다. 모든 국가를 보려면 슬라이싱을 제거하세요

```sh
<Response [200]>
200
[{'alpha2Code': 'AF',
  'alpha3Code': 'AFG',
  'altSpellings': ['AF', 'Afġānistān'],
  'area': 652230.0,
  'borders': ['IRN', 'PAK', 'TKM', 'UZB', 'TJK', 'CHN'],
  'callingCodes': ['93'],
  'capital': 'Kabul',
  'cioc': 'AFG',
  'currencies': [{'code': 'AFN', 'name': 'Afghan afghani', 'symbol': '؋'}],
  'demonym': 'Afghan',
  'flag': 'https://restcountries.eu/data/afg.svg',
  'gini': 27.8,
  'languages': [{'iso639_1': 'ps',
                 'iso639_2': 'pus',
                 'name': 'Pashto',
                 'nativeName': 'پښتو'},
                {'iso639_1': 'uz',
                 'iso639_2': 'uzb',
                 'name': 'Uzbek',
                 'nativeName': 'Oʻzbek'},
                {'iso639_1': 'tk',
                 'iso639_2': 'tuk',
                 'name': 'Turkmen',
                 'nativeName': 'Türkmen'}],
  'latlng': [33.0, 65.0],
  'name': 'Afghanistan',
  'nativeName': 'افغانستان',
  'numericCode': '004',
  'population': 27657145,
  'region': 'Asia',
  'regionalBlocs': [{'acronym': 'SAARC',
                     'name': 'South Asian Association for Regional Cooperation',
                     'otherAcronyms': [],
                     'otherNames': []}],
  'subregion': 'Southern Asia',
  'timezones': ['UTC+04:30'],
  'topLevelDomain': ['.af'],
  'translations': {'br': 'Afeganistão',
                   'de': 'Afghanistan',
                   'es': 'Afganistán',
                   'fa': 'افغانستان',
                   'fr': 'Afghanistan',
                   'hr': 'Afganistan',
                   'it': 'Afghanistan',
                   'ja': 'アフガニスタン',
                   'nl': 'Afghanistan',
                   'pt': 'Afeganistão'}}]
```


JSON 데이터를 가져오는 경우 response 객체에서 _json()_ 메서드를 사용합니다. txt, html, xml 및 기타 파일 형식의 경우 _text_를 사용할 수 있습니다.

### 패키지 만들기

많은 수의 파일을 일정한 기준에 따라 다른 폴더와 하위 폴더로 구성하여 쉽게 찾고 관리할 수 있습니다. 아시다시피 모듈은 클래스, 함수 등 여러 객체를 포함할 수 있습니다. 패키지는 하나 이상의 관련 모듈을 포함할 수 있습니다. 패키지는 실제로 하나 이상의 모듈 파일을 포함하는 폴더입니다. 다음 단계를 사용하여 mypackage라는 패키지를 만들어 봅시다:

30DaysOfPython 폴더 안에 mypackage라는 새 폴더를 만드세요
mypackage 폴더에 빈 **__init__**.py 파일을 만드세요.
다음 코드로 arithmetic.py 및 greet.py 모듈을 만드세요:

In [ ]:
# mypackage/arithmetics.py
# arithmetics.py
def add_numbers(*args):
    total = 0
    for num in args:
        total += num
    return total


def subtract(a, b):
    return (a - b)


def multiple(a, b):
    return a * b


def division(a, b):
    return a / b


def remainder(a, b):
    return a % b


def power(a, b):
    return a ** b

In [ ]:
# mypackage/greet.py
# greet.py
def greet_person(firstname, lastname):
    return f'{firstname} {lastname}, welcome to 30DaysOfPython Challenge!'


패키지의 폴더 구조는 다음과 같아야 합니다:

```sh
─ mypackage
    ├── __init__.py
    ├── arithmetic.py
    └── greet.py
```


이제 Python 대화형 셸을 열고 우리가 만든 패키지를 사용해 봅시다:

```sh
asabeneh@Asabeneh:~/Desktop/30DaysOfPython$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mypackage import arithmetics
>>> arithmetics.add_numbers(1, 2, 3, 5)
11
>>> arithmetics.subtract(5, 3)
2
>>> arithmetics.multiple(5, 3)
15
>>> arithmetics.division(5, 3)
1.6666666666666667
>>> arithmetics.remainder(5, 3)
2
>>> arithmetics.power(5, 3)
125
>>> from mypackage import greet
>>> greet.greet_person('Asabeneh', 'Yetayeh')
'Asabeneh Yetayeh, welcome to 30DaysOfPython Challenge!'
>>>
```


보시다시피 패키지가 완벽하게 작동합니다. 패키지 폴더에는 **__init__**.py라는 특별한 파일이 있으며 패키지의 내용을 저장합니다. 패키지 폴더에 **__init__**.py를 넣으면 Python이 이를 패키지로 인식하기 시작합니다.
**__init__**.py는 해당 모듈의 지정된 리소스를 다른 Python 파일에서 임포트할 수 있도록 노출합니다. 빈 **__init__**.py 파일은 패키지가 임포트될 때 모든 함수를 사용 가능하게 만듭니다. **__init__**.py는 폴더가 Python에서 패키지로 인식되는 데 필수적입니다.

### 패키지에 대한 추가 정보

- 데이터베이스
  - SQLAlchemy 또는 SQLObject - 여러 다른 데이터베이스 시스템에 대한 객체 지향 접근
    - _pip install SQLAlchemy_
- 웹 개발
  - Django - 고수준 웹 프레임워크
    - _pip install django_
  - Flask - Werkzeug, Jinja 2 기반의 Python 마이크로 프레임워크 (BSD 라이선스)
    - _pip install flask_
- HTML 파서
  - [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) - 스크린 스크래핑과 같은 빠른 프로젝트를 위해 설계된 HTML/XML 파서, 잘못된 마크업도 허용
    - _pip install beautifulsoup4_
  - PyQuery - Python에서 jQuery를 구현, BeautifulSoup보다 빠르다고 함

- XML 처리
  - ElementTree - Element 타입은 간단하지만 유연한 컨테이너 객체로, 메모리에 간소화된 XML 정보셋과 같은 계층적 데이터 구조를 저장하도록 설계됨 --참고: Python 2.5 이상에서 ElementTree가 표준 라이브러리에 포함됨
- GUI
  - PyQt - 크로스 플랫폼 Qt 프레임워크 바인딩
  - TkInter - 전통적인 Python 사용자 인터페이스 툴킷
- 데이터 분석, 데이터 과학 및 머신 러닝
  - Numpy: Numpy(numeric python)는 Python에서 가장 인기 있는 머신 러닝 라이브러리 중 하나로 알려져 있습니다.
  - Pandas: Python에서 고수준 데이터 구조와 다양한 분석 도구를 제공하는 데이터 분석, 데이터 과학 및 머신 러닝 라이브러리입니다.
  - SciPy: SciPy는 애플리케이션 개발자와 엔지니어를 위한 머신 러닝 라이브러리입니다. SciPy 라이브러리에는 최적화, 선형 대수, 적분, 이미지 처리 및 통계 모듈이 포함되어 있습니다.
  - Scikit-Learn: NumPy와 SciPy 기반입니다. 복잡한 데이터를 처리하기 위한 최고의 라이브러리 중 하나로 간주됩니다.
  - TensorFlow: Google에서 만든 머신 러닝 라이브러리입니다.
  - Keras: Python에서 가장 멋진 머신 러닝 라이브러리 중 하나로 간주됩니다. 신경망을 표현하기 위한 더 쉬운 메커니즘을 제공합니다. Keras는 또한 모델 컴파일, 데이터셋 처리, 그래프 시각화 등을 위한 최고의 유틸리티를 제공합니다.
- 네트워크:
  - requests: 서버에 요청(GET, POST, DELETE, PUT)을 보내는 데 사용할 수 있는 패키지입니다
    - _pip install requests_

🌕 항상 발전하고 있으며 위대함을 향한 20단계 앞서 있습니다. 이제 두뇌와 근육을 위한 연습을 해보세요.

## 연습문제: Day 20

1. 이 url을 읽고 가장 빈도가 높은 10개의 단어를 찾으세요. romeo_and_juliet = 'http://www.gutenberg.org/files/1112/1112.txt'
2. 고양이 API를 읽고 cats_api = 'https://api.thecatapi.com/v1/breeds' 다음을 찾으세요:
   1. 미터법 단위에서 고양이 체중의 최솟값, 최댓값, 평균, 중앙값, 표준 편차
   2. 고양이 수명(년)의 최솟값, 최댓값, 평균, 중앙값, 표준 편차
   3. 고양이의 국가와 품종의 빈도 테이블을 만드세요
3. [국가 API](https://restcountries.eu/rest/v2/all)를 읽고 다음을 찾으세요
   1. 10개의 가장 큰 국가
   2. 10개의 가장 많이 사용되는 언어
   3. 국가 API에 있는 총 언어 수
4. UCI는 데이터 과학 및 머신 러닝을 위한 데이터셋을 얻을 수 있는 가장 일반적인 장소 중 하나입니다. UCL의 콘텐츠를 읽어보세요 (https://archive.ics.uci.edu/ml/datasets.php). 추가 라이브러리 없이는 어려울 수 있으므로 BeautifulSoup4로 시도해 볼 수 있습니다.

🎉 축하합니다! 🎉

[<< Day 19](../19_Day_File_handling/19_file_handling.md) | [Day 21 >>](../21_Day_Classes_and_objects/21_classes_and_objects.md)